# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'Xcode9to10Preparation', :path => ".."
end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = '$(inherited) XCODE_10_ENVIRONMENT'
#        end
#    end
#end
